"""
glycosignal.report
==================

Summary report generation for CGM data.

Produces an HTML report containing:
  - Summary statistics table
  - Time-in-range metrics table
  - Risk index table
  - AGP plot (embedded as base64 PNG)
  - Glucose time series plot (embedded as base64 PNG)

Usage
-----
    >>> from glycosignal import report
    >>> report.generate_summary_report(df, output_path="report.html")
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

import pandas as pd

from . import metrics, plotting
from .schemas import COL_GLUCOSE, COL_TIMESTAMP
from .utils import require_columns, require_dataframe


# ─────────────────────────────────────────────────────────────────────────────
# Plot helpers
# ─────────────────────────────────────────────────────────────────────────────

def _fig_to_base64(fig) -> str:
    """Encode a matplotlib figure as a base64 PNG string."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120, bbox_inches="tight")
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode("utf-8")
    buf.close()
    try:
        import matplotlib.pyplot as plt
        plt.close(fig)
    except Exception:
        pass
    return b64


def _make_plots_b64(df: pd.DataFrame) -> tuple[str, str]:
    """Generate AGP and time series plots and return as base64 strings."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        fig_ts, _ = plotting.plot_glucose_timeseries(df, show_tir_bands=True)
        ts_b64 = _fig_to_base64(fig_ts)

        fig_agp, _ = plotting.plot_agp(df)
        agp_b64 = _fig_to_base64(fig_agp)

        return ts_b64, agp_b64
    except Exception:
        return "", ""


# ─────────────────────────────────────────────────────────────────────────────
# HTML template
# ─────────────────────name────────────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GlycoSignal CGM Summary Report</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 960px; margin: 0 auto;
          padding: 24px; background: #f5f7fa; color: #1a1a2e; }}
  h1   {{ color: #1565c0; border-bottom: 2px solid #1565c0; padding-bottom: 8px; }}
  h2   {{ color: #1565c0; margin-top: 32px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 24px;
           background: #ffffff; border-radius: 8px; overflow: hidden;
           box-shadow: 0 1px 4px rgba(0,0,0,0.10); }}
  th   {{ background: #1565c0; color: white; padding: 10px 14px; text-align: left; font-size: 0.9em; }}
  td   {{ padding: 8px 14px; border-bottom: 1px solid #e8eaf6; font-size: 0.9em; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #e8eaf6; }}
  .metric-value {{ font-weight: bold; text-align: right; }}
  .badge-green  {{ background:#c8e6c9; color:#1b5e20; border-radius:4px; padding:2px 6px; }}
  .badge-yellow {{ background:#fff9c4; color:#f57f17; border-radius:4px; padding:2px 6px; }}
  .badge-red    {{ background:#ffcdd2; color:#b71c1c; border-radius:4px; padding:2px 6px; }}
  img.plot {{ width: 100%; max-width: 900px; border-radius: 8px;
              box-shadow: 0 1px 4px rgba(0,0,0,0.12); margin: 8px 0 24px 0; }}
  .footer {{ color: #9e9e9e; font-size: 0.8em; margin-top: 32px; border-top: 1px solid #e0e0e0; padding-top: 12px; }}
</style>
</head>
<body>
<h1>GlycoSignal CGM Summary Report</h1>
<p><strong>Generated:</strong> {generated_at}</p>
<p><strong>Period:</strong> {period_start} &ndash; {period_end} ({duration_days:.1f} days, {n_readings} readings)</p>

<h2>Summary Statistics</h2>
{stats_table}

<h2>Time-in-Range</h2>
{tir_table}

<h2>Risk Indices</h2>
{risk_table}

<h2>Glucose Time Series</h2>
{ts_plot}

<h2>Ambulatory Glucose Profile (AGP)</h2>
{agp_plot}

<div class="footer">Generated by GlycoSignal &bull; https://github.com/glycosignal/glycosignal</div>
</body>
</html>
"""


def _table_html(rows: list[tuple[str, str, str]], headers: tuple[str, str, str]) -> str:
    """Render a simple two-column HTML table."""
    rows_html = "\n".join(
        f"<tr><td>{label}</td><td class='metric-value'>{value}</td><td>{note}</td></tr>"
        for label, value, note in rows
    )
    return (
        f"<table><thead><tr>"
        f"<th>{headers[0]}</th><th>{headers[1]}</th><th>{headers[2]}</th>"
        f"</tr></thead><tbody>{rows_html}</tbody></table>"
    )


def _img_tag(b64: str) -> str:
    if not b64:
        return "<p><em>Plot unavailable (matplotlib error)</em></p>"
    return f'<img class="plot" src="data:image/png;base64,{b64}" alt="plot" />'


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def generate_summary_report(
    df: pd.DataFrame,
    output_path: str | Path | None = None,
    format: str = "html",
    subject: str | None = None,
) -> str:
    """Generate a CGM summary report and optionally save it to disk.

    Parameters
    ----------
    df : pd.DataFrame
        CGM data with ``Timestamp`` and ``Glucose`` columns.
    output_path : str | Path | None
        If provided, the report HTML is written to this file.
    format : str
        Output format.  Currently only ``"html"`` is supported.
    subject : str | None
        Optional subject label shown in the report title.

    Returns
    -------
    str
        The generated HTML string.

    Raises
    ------
    ValueError
        If *format* is not ``"html"``.
    """
    require_dataframe(df, "df")
    require_columns(df, [COL_TIMESTAMP, COL_GLUCOSE])

    if format != "html":
        raise ValueError(f"Only format='html' is currently supported, got {format!r}.")

    from datetime import datetime

    ts = pd.to_datetime(df[COL_TIMESTAMP], errors="coerce")
    gl = pd.to_numeric(df[COL_GLUCOSE], errors="coerce")
    valid = ts.notna() & gl.notna()
    ts_valid = ts[valid]
    n_readings = int(valid.sum())

    period_start = ts_valid.min().strftime("%Y-%m-%d") if n_readings else "N/A"
    period_end = ts_valid.max().strftime("%Y-%m-%d") if n_readings else "N/A"
    duration_days = (
        (ts_valid.max() - ts_valid.min()).total_seconds() / 86400
        if n_readings >= 2 else 0.0
    )

    # Compute metrics
    d = df[[COL_TIMESTAMP, COL_GLUCOSE]].copy()
    from .schemas import prepare
    prep = prepare(d)

    def _fmt(v, digits=1):
        if v is None or (isinstance(v, float) and pd.isna(v)):
            return "N/A"
        return f"{v:.{digits}f}"

    stats_rows = [
        ("Mean glucose", _fmt(metrics.mean_glucose(prep)), "mg/dL"),
        ("Median glucose", _fmt(metrics.median_glucose(prep)), "mg/dL"),
        ("Min glucose", _fmt(metrics.min_glucose(prep)), "mg/dL"),
        ("Max glucose", _fmt(metrics.max_glucose(prep)), "mg/dL"),
        ("Q1 (25th %ile)", _fmt(metrics.q1_glucose(prep)), "mg/dL"),
        ("Q3 (75th %ile)", _fmt(metrics.q3_glucose(prep)), "mg/dL"),
        ("SD", _fmt(metrics.sd(prep)), "mg/dL"),
        ("CV", _fmt(metrics.cv(prep)), "%"),
        ("J-index", _fmt(metrics.j_index(prep)), ""),
        ("MAGE", _fmt(metrics.mage(prep)), "mg/dL"),
    ]

    tir_rows = [
        ("Time in Target 70–180 mg/dL", _fmt(metrics.time_in_range_percent(prep, 70, 180)), "%"),
        ("Time in Tight 70–140 mg/dL", _fmt(metrics.time_in_range_percent(prep, 70, 140)), "%"),
        ("Time Below 70 mg/dL (L1 Hypo)", _fmt(metrics.time_below_range_percent(prep, 70)), "%"),
        ("Time Below 54 mg/dL (L2 Hypo)", _fmt(metrics.time_below_range_percent(prep, 54)), "%"),
        ("Time Above 180 mg/dL (L1 Hyper)", _fmt(metrics.time_above_range_percent(prep, 180)), "%"),
        ("Time Above 250 mg/dL (L2 Hyper)", _fmt(metrics.time_above_range_percent(prep, 250)), "%"),
    ]

    risk_rows = [
        ("LBGI (Low BG Index)", _fmt(metrics.lbgi(prep)), "higher = more hypo risk"),
        ("HBGI (High BG Index)", _fmt(metrics.hbgi(prep)), "higher = more hyper risk"),
        ("ADRR", _fmt(metrics.adrr(prep)), "daily risk range"),
        ("GRI (Glucose Risk Index)", _fmt(metrics.gri(prep)), "0–100; higher = more risk"),
    ]

    stats_table = _table_html(stats_rows, ("Metric", "Value", "Unit"))
    tir_table = _table_html(tir_rows, ("Metric", "Value", "Unit"))
    risk_table = _table_html(risk_rows, ("Metric", "Value", "Note"))

    # Generate plots
    ts_b64, agp_b64 = _make_plots_b64(df)
    ts_plot = _img_tag(ts_b64)
    agp_plot = _img_tag(agp_b64)

    html = _HTML_TEMPLATE.format(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        period_start=period_start,
        period_end=period_end,
        duration_days=duration_days,
        n_readings=n_readings,
        stats_table=stats_table,
        tir_table=tir_table,
        risk_table=risk_table,
        ts_plot=ts_plot,
        agp_plot=agp_plot,
    )

    if output_path is not None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")

    return html
